[workspace.package]
version = "0.1.3"
edition = "2024"
description = "Simple, in-memory async task queue for Rust."
repository = "https://github.com/wizrds/jobq-rs"
license = "ISC"
readme = "README.md"

[workspace]
resolver = "2"
members = [
    "jobq-core",
    "jobq",
]

[workspace.dependencies]
async-trait = { version = "0.1" }
futures = { version = "0.3" }
futures-timeout = { version = "0.1" }

thiserror = { version = "2.0" }
anyhow = { version = "1.0" }

mea = { version = "0.6" }