[package]
name = "jobq-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
async-trait = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
mea = { workspace = true }
futures = { workspace = true }
futures-timeout = { workspace = true }
event-listener = { version = "5.4.1" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }