name: default

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@v3
        with:
          version: 3.43.3

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Lint commit message
        run: |
          pip install gitlint
          git log -1 --pretty=%B | gitlint

      - name: Lint code
        run: task rust:lint

      - name: Format code
        run: task rust:fmt

  tests:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@v3
        with:
          version: 3.43.3

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Unit tests
        run: task rust:test
